Feature/migrate signing box to new dss
Fedict/eid-dss pull request #13
Opened 2016-09-23 13:33 UTC by janvdbergh

2016-09-26 09:40 UTC, hansvandenbroeck commented on eid-dss-portal-control/src/test/java/TestJan.java
> +public class TestJan {
TestJan?

2016-09-26 09:46 UTC, hansvandenbroeck commented on eid-dss-portal-control/src/main/java/be/fedict/eid/dss/portal/servlet/SignatureResponseServlet.java
> +public class SignatureResponseServlet extends HttpServlet {
Is there a test for this?

2016-09-26 09:46 UTC, hansvandenbroeck commented on eid-dss-portal-control/src/main/java/be/fedict/eid/dss/portal/control/state/SigningModelRepository.java
> +public class SigningModelRepository {
test?

2016-09-26 09:47 UTC, hansvandenbroeck requested changes
Is it possible I miss some tests?

2016-09-27 07:23 UTC, janvdbergh commented on eid-dss-portal-control/src/test/java/TestJan.java
> +public class TestJan {
Removed it.

2016-09-27 07:23 UTC, janvdbergh commented on eid-dss-portal-control/src/main/java/be/fedict/eid/dss/portal/servlet/SignatureResponseServlet.java
> +public class SignatureResponseServlet extends HttpServlet {
Codebase does not have tests :)

2016-09-27 07:23 UTC, janvdbergh commented on eid-dss-portal-control/src/main/java/be/fedict/eid/dss/portal/control/state/SigningModelRepository.java
> +public class SigningModelRepository {
Codebase does not have tests :)

2016-10-07 11:34 UTC, merged